SHOW DATABASES;

CREATE DATABASE go_taipei;
DROP DATABASE go_taipei;
USE go_taipei;

SHOW TABLES;

CREATE TABLE attractions(
	aid INT PRIMARY KEY AUTO_INCREMENT,
	id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_id INT NOT NULL,
    description VARCHAR(5000) NOT NULL,
    address VARCHAR(255) NOT NULL,
    transport VARCHAR(1000) NOT NULL,	
    mrt_id INT NOT NULL,
    lat VARCHAR(255) NOT NULL,
    lng VARCHAR(255) NOT NULL
);

CREATE TABLE categories(
	cid INT PRIMARY KEY AUTO_INCREMENT,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE mrts(
	mid INT PRIMARY KEY AUTO_INCREMENT,
    mrt_name VARCHAR(255)
);

CREATE TABLE images(
	pid INT PRIMARY KEY AUTO_INCREMENT,
	iid INT NOT NULL,
    url text NOT NULL
);


SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
SET GLOBAL group_concat_max_len=100000;

SELECT * FROM attractions;
SELECT * FROM categories;
SELECT * FROM mrts;
SELECT * FROM images;


DROP TABLE attractions;
DROP TABLE categories;
DROP TABLE mrts;
DROP TABLE images;



CREATE TABLE users( 
	uid INT PRIMARY KEY AUTO_INCREMENT, 
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM users;

DROP TABLE users;